import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const sourceUrl = new URL('../src/host-profile-menu.ts', import.meta.url)

test('native Back closes the shell-owned device menu before exiting', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.ok(source.includes("import { MOBILE_PLATFORM_BACK_EVENT } from './platform-back.ts'"))
  assert.ok(source.includes("document.addEventListener(MOBILE_PLATFORM_BACK_EVENT, onPlatformBack)"))
  assert.ok(source.includes('function onPlatformBack(event: Event): void {\n    event.preventDefault()\n    close()\n  }'))
  assert.ok(source.includes("document.removeEventListener(MOBILE_PLATFORM_BACK_EVENT, onPlatformBack)"))
})

test('successful QR pairing closes the menu instead of leaving the camera-opening state visible', async () => {
  const main = await readFile(new URL('../src/main.ts', import.meta.url), 'utf8')
  assert.match(main, /menu\?\.close\(\)\s*await onPairOffer\(offer\)/)
})

test('expired Host codes ask the user to wait for a fresh QR', async () => {
  const main = await readFile(new URL('../src/main.ts', import.meta.url), 'utf8')
  assert.match(main, /二维码已过期，请等电脑画面更新后再扫/)
})

test('Host switch reconnect failures stay on the switch progress surface', async () => {
  const main = await readFile(new URL('../src/main.ts', import.meta.url), 'utf8')
  assert.ok(main.includes('reconnect: () => onActiveHostChanged(true)'))
  assert.ok(main.includes('async function reconnectActiveHost(propagateError = false)'))
  assert.ok(main.includes('if (propagateError) throw error'))
})

test('device panel puts scan in the header, scrolls the device list, and sinks settings', async () => {
  const source = await readFile(sourceUrl, 'utf8')
  assert.ok(source.includes('--dsh-profile-top-clearance: max(40px, calc(env(safe-area-inset-top) + 12px))'))
  assert.ok(source.includes('overflow: hidden;'))
  assert.ok(source.includes('display: flex;'))
  assert.ok(source.includes('flex-direction: column;'))
  assert.ok(source.includes('width: 24px;'))
  assert.ok(source.includes('height: 24px;'))
  assert.ok(source.includes('border-radius: 26px;'))
  assert.ok(!source.includes('border-bottom: 0;'))
  assert.ok(source.includes('[data-profile-close]:hover'))
  assert.ok(source.includes('-webkit-tap-highlight-color: transparent;'))
  assert.ok(source.includes('box-shadow: none;'))
  assert.ok(!source.includes('box-shadow: 0 0 0 1px var(--dsw-alias-state-business-primary'))
  assert.ok(source.includes('deviceList.dataset.profileDeviceList'))
  assert.ok(source.includes('[data-profile-device-list]'))
  assert.ok(source.includes('flex: 1 1 auto;'))
  assert.ok(source.includes('overflow-y: auto;'))
  assert.ok(source.includes('overscroll-behavior: contain;'))
  assert.ok(source.includes('align-items: center;'))
  assert.ok(source.includes('max-height: calc(100dvh - var(--dsh-profile-top-clearance) - var(--dsh-profile-bottom-clearance));'))
  assert.ok(!source.includes("button('移除'"))
  assert.ok(!source.includes('data-profile-device-actions'))
  assert.ok(source.includes("setAttribute('aria-label', '移除' + profile.displayName)"))
  assert.ok(source.includes('deviceHead.append(remove)'))
  assert.ok(source.includes('REMOVE_ICON'))
  assert.ok(!source.includes('data-profile-multiple'))
  assert.ok(!source.includes('[data-profile-multiple]'))
  assert.ok(!source.includes('已配对设备'))
  assert.ok(!source.includes('会话体验模式'))
  assert.ok(!source.includes('SessionEnhancementPreference'))
  assert.ok(!source.includes('onEnhancementChange'))
  assert.ok(source.includes('扫码添加或重新配对'))
  assert.ok(source.includes('data-profile-scan-button'))
  assert.ok(source.includes('data-profile-add-device'))
  assert.ok(source.includes("textContent = '添加设备'"))
  assert.ok(source.includes('扫码添加另一台电脑'))
  assert.ok(source.includes('点「添加设备」扫码连接另一台电脑'))
  assert.ok(source.includes('data-profile-settings'))
  assert.ok(source.includes('后台连接保护（实验）'))
  assert.ok(source.includes('Android 会显示常驻通知'))
  assert.ok(source.includes('系统仍可能终止进程'))
  assert.ok(source.includes('还没有已保存设备'))
  assert.ok(!source.includes('点右上角扫码添加'))
  assert.ok(source.includes('runHostProfileSwitch(profile, options.onActivate'))
  assert.ok(source.includes('当前连接'))
  assert.ok(source.includes('正在切换 Host'))
  assert.ok(source.includes('runHostProfileSwitch'))
  const nameStyleStart = source.indexOf('[data-profile-device-name]')
  const nameStyle = source.slice(nameStyleStart, source.indexOf('}', nameStyleStart))
  assert.ok(nameStyle.includes('font-size: 16px;'))
  assert.ok(nameStyle.includes('white-space: normal;'))
  assert.ok(source.includes('endpoint.textContent = endpointLabel(profile)'))
  assert.ok(source.includes('data-profile-chrome-health'))
  assert.ok(source.includes('部分界面增强不可用') === false)
  assert.ok(source.includes('chromeHealth'))
  assert.ok(!source.includes('data-profile-scan-card'))
  assert.ok(!source.includes('data-profile-status-card'))
  assert.ok(!source.includes('重新扫码配对'))
})
